add array formating functionnal and push missing movielabs schema
trackit/mddf-parser pull request #12
Opened 2023-07-04 14:53 UTC by ThomyLorenzatti

2023-07-04 15:36 UTC, GautierBlandin requested changes
There are some flaws in the logic. Add some slightly more complex tests to check.

2023-07-04 15:36 UTC, GautierBlandin commented on src/SchemaConformer/SchemaConformer.ts
> +      if (Array.isArray(currentObject)) {
There is something wrong with this recursion step. If currentObject is an array, its element are not valid pathStep and ```currentObject.forEach((pathStep: PathStep)``` is invalid. Additionally, according to our principle of post-order traversal, the recursion should occur first, and the conform after.

2023-07-04 15:36 UTC, GautierBlandin commented on src/SchemaConformer/SchemaConformer.ts
> +  public conformArrayCharKey(rawObject: unknown): Primitive[] {
This function should not exist. This should already be handled by conform primitive, and they're is no need for a dedicated array function for that.

What should happen is as follow:
If you are within an array, you iterate other the elements and you conformRecursive them. Then, when the recursion gets to each element, if the element has a primitive schema, the conformPrimitive function should take care of transforming the (false) object element into a primitive type.

To give you a better idea, imagine you have the following array:
[{Value: 'foo'}, {Value: 'bar'}, {Value: 'baz'}] that you want turned into ['foo', 'bar', 'baz'].

You should iterate over the array, applying conform recursive at each element. Then, the conformRecursive function is going to look at {Value: 'foo'} and transform it into 'foo' (at this point, the array will look like this:
['foo', {Value: 'bar'}, {Value: 'baz'}]. Then, the conform recursive function will take care of { Value: 'bar' }, etc...

2023-07-06 12:42 UTC, pierreSchrothDev commented on src/SchemaConformer/SchemaConformer.ts
> +  private handleObjectForObjectSchema(rawObject: Record<string, unknown>, currentObject: unknown, pathStack: PathStep[]): void {
Wich handle type ? What are you doing when you "handle" the object.
-> Try to rename the function

2023-07-06 12:43 UTC, pierreSchrothDev reviewed
Good file organization, efficient functions name.

2023-07-06 13:18 UTC, GautierBlandin requested changes

2023-07-06 13:18 UTC, GautierBlandin commented on src/SchemaConformer/SchemaConformer.ts
>        this.objectUtils.setDeepProperty(rawObject, pathStack, this.conformPrimitive(currentObject));
There is a discrepency between the meaning of conformPrimitive and conformArray. Conform array updates the object to what we expect and returns it, while conform array does much more logic and recursion steps. 

I think that conformArray is fine as it is, but then conformPrimitive should be updated to take in rawObject and pathStack.

2023-07-06 13:18 UTC, GautierBlandin commented on src/SchemaConformer/SchemaConformer.ts
> +      this.handleObjectForObjectSchema(rawObject, currentObject, pathStack);
If we are using conformArray and conformPrimitive, we should use conformObject instead of handleObjectForObjectSchema

2023-07-06 13:18 UTC, GautierBlandin commented on src/SchemaConformer/SchemaConformer.ts
> +      this.conformRecursive(rawObject, this.appendToPathStack(pathStack, lastStep));
appendToPathStack is badly named, as it does not acutally append to the pathStack, but replaces the last step of the pathStack with lastStep. Choose a name that makes this explicit, like replaceLastPathStep

2023-07-06 13:18 UTC, GautierBlandin commented on src/SchemaConformer/SchemaConformer.ts
> +  private handleArrayForArraySchema(rawObject: Record<string, unknown>, currentObject: unknown[], pathStack: PathStep[]): void {
Avoid handle as much as possible as it's a very generic name that doesn't indicate what the function does. What this function does is that it iterates over the array and launch the recursion on each item. Maybe you could name it recurseOverArray, recurseOnEveryItem, or something like that.

2023-07-06 13:18 UTC, GautierBlandin commented on src/SchemaConformer/SchemaConformer.ts
> +  private handleObjectForArraySchema(rawObject: Record<string, unknown>, currentObject: object, pathStack: PathStep[]): void {
Same thing about handle, handle is too generic. What this function does is that it wraps the object in a single element array and then continues the recursion. Use a name that reflects that.

2023-07-06 13:18 UTC, GautierBlandin commented on src/SchemaConformer/SchemaConformer.ts
> +  private appendToPathStack(pathStack: ObjectPath, lastStep: PathStep): PathStep[] {
Rename to replace lastPathStep

2023-07-06 13:18 UTC, GautierBlandin commented on src/SchemaConformer/SchemaConformer.ts
> +    return Array.isArray(rawObject) && rawObject.length > 0;
Why is it necessary to check the array has length at least 1 ? Empty arrays exist and have length 0 while being valid array, so this requirements is odd. If you actually intend this requirement for logical reason, either move it to a separate function or change the name of the function (isNonEmtpyArray)

2023-07-06 13:18 UTC, GautierBlandin commented on src/SchemaUtils/SchemaUtils.ts
> +      if (this.isCurrentArray(current, part.propertyName)) {
This function should be renamed as isCurrentArray doesn't mean much (it should not reference the name of the current variable)

2023-07-06 20:10 UTC, GautierBlandin approved these changes
LGTM

2023-07-06 20:10 UTC, merged